## COMMON ##
vertice_dim: 18516
feature_dim: 256
gru_dim: 256
gru_layers: 2
model: "multiface"
input_fps: 50
output_fps: 30
diff_steps: 1000
skip_steps: 0
num_samples: 1


## DATASET
dataset: "multiface"
train_subjects: "2 3 6 7 9 10 11 12 13"
val_subjects: "2 4 6 8"
test_subjects: "1 4 5 8"
## PATH ##
gt_path:  "data/multiface/vertices_npy/"
region_path: "data/multiface/regions/"
template_file: "templates.pkl"

## COMMON PATH ##
data_path: "data"
wav_path: "wav"
vertices_path: "vertices_npy"
save_path: "save"
result_path: "result"


## TRAINING ##
lr: 0.0001
gradient_accumulation_steps: 1
max_epoch: 50  
device: "cuda"
beta_type: "linear"   ## "cosine","linear"








